name: Export my notion workspace

on:

  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "d6fbc097-00d2-4176-9e1c-24c8d94aad4b,d9c29158-8810-4a32-9fdf-d2a6fa7dd08b"  # Pages IDs identified in (step 2)  
          output-dir: notion-backup
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
